# Site
repository: PriyankaBulla/PriyankaBulla.github.io
#favicon: images/favicon.ico

# Personal info
name: Priyanka Bulla
title: MS in Information Technology and Management (Data Management)
email: pbulla@hawk.iit.edu
phone: 312-868-8747
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  PriyankaBulla
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: priyanka0507
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Priyanka Bulla, currently pursuing a masters in Information Technology and Management. Having taken up courses like Data Analytics, Data Warehousing, Data Mining, and Project Management, I am more inclined towards working with Data, designing and delivering analytics and insights using various analytical tools to enable reporting and planning.
  
  I will be graduating from the Illinois Institute of Technology in May 2020 with a master’s degree in Information Technology and Management with Data Management as my major. I am looking for internships and full-time analyst opportunities. I hope I am given an opportunity to prove to you that I possess the exact skill set and outlook you’re looking for.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   - **Data** **Management**: Database Design and Management, Data Analysis, Pattern and Trend Identification, Visualization and Data Insights, Data Warehousing, Data Mining, Regression Analysis, Data Modeling, Predictive Analytics
   - **Programming** **Languages**: C,C++,Java, SQL
   - **Web Technology**: HTML5, CSS, JavaScript
   - **Data Visualization**: Excel, Tableau, PowerBI, Pentaho CDE
   - **BI and Reporting tools**: MS Power BI, Tableau, Excel VBA, VLOOKUP
   - **Data Analytics**: Excel, R, SQL, Python, Saiku Analytics
   - **Database**: MS Access, Oracle SQL developer, MYSQL, MS SQL
   - **ETL Tools**: MS SSIS, Pentaho
   - **Web Analytics**: Google Analytics

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
